### ISSUE TITLE
Add print styles FAQ

### ISSUE THREAD

**Issue by philbuchanan** [philbuchanan/Accordion-Shortcodes#65]
Should include this code:

```css
@media print {
	.accordion-content {
		display: block !important;
	}
}
```
