### ISSUE TITLE
Hide all content by default with display: none

### ISSUE THREAD

**Issue by philbuchanan** [philbuchanan/Accordion-Shortcodes#75]
This will remove the _flash_ of seeing all accordion item's content when the page is loading. Then swap the plugin to `openItem()` instead of `closeItem()` on load.

Use the `no-js` CSS class to force them open in CSS:

```css
.no-js .c-accordion__content {
    display: block !important;
}
```
